# Generated by Django 6.0.4 on 2026-08-07 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0003_seed_initial_rewards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price_at_order', models.PositiveIntegerField(help_text='1 dona narxining sotib olingan paytdagi nusxasi')),
                ('total_price', models.PositiveIntegerField()),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('active', 'Kutilmoqda'), ('issued', 'Berildi'), ('expired', "Muddati o'tdi")], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='rewards.reward')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
