# Generated by Django 6.0.4 on 2026-08-05 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_1_normal', models.PositiveIntegerField(default=5)),
                ('place_2_normal', models.PositiveIntegerField(default=4)),
                ('place_3_normal', models.PositiveIntegerField(default=3)),
                ('effort_min_normal', models.PositiveIntegerField(default=1)),
                ('effort_max_normal', models.PositiveIntegerField(default=2)),
                ('place_1_big', models.PositiveIntegerField(default=10)),
                ('place_2_big', models.PositiveIntegerField(default=8)),
                ('place_3_big', models.PositiveIntegerField(default=6)),
                ('effort_min_big', models.PositiveIntegerField(default=2)),
                ('effort_max_big', models.PositiveIntegerField(default=4)),
                ('individual_normal', models.PositiveIntegerField(default=3)),
                ('individual_big', models.PositiveIntegerField(default=6)),
                ('big_days', models.CharField(default='4,5', help_text='Vergul bilan ajratilgan hafta kunlari: 0=dushanba ... 6=yakshanba', max_length=20)),
                ('min_group_for_3rd', models.PositiveIntegerField(default=6)),
                ('max_games_per_week', models.PositiveIntegerField(default=3)),
                ('edit_window_hours', models.PositiveIntegerField(default=24)),
                ('purchase_expires_days', models.PositiveIntegerField(default=14)),
            ],
            options={
                'verbose_name': 'Tangacha sozlamasi',
                'verbose_name_plural': 'Tangacha sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('game_place', "O'yin — o'rin"), ('game_effort', "O'yin — harakat"), ('purchase', 'Xarid'), ('refund', 'Qaytarish'), ('adjustment', 'Tuzatish')], max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='coins_coint_student_f89dec_idx')],
            },
        ),
    ]
