# Generated by Django 6.0.4 on 2026-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinsetting',
            name='coin_value_som',
            field=models.PositiveIntegerField(default=0, help_text="1 tangachaning taxminiy real qiymati (so'mda) — faqat hisobot sahifasida ishlatiladi."),
        ),
    ]
