# Generated by Django 6.0.4 on 2026-08-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coinsetting_coin_value_som'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinsetting',
            name='coin_value_som',
        ),
    ]
