# Generated by Django 6.0.4 on 2026-04-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_coins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at']},
        ),
    ]
