# Generated by Django 6.0.4 on 2026-05-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='class_days',
            field=models.JSONField(blank=True, default=list, help_text='List of weekday ints: 0=Mon … 6=Sun'),
        ),
    ]
