# Generated by Django 6.0.4 on 2026-05-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_add_class_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
