# Generated by Django 6.0.4 on 2026-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_exam_examresult_group_exam_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='absent',
            field=models.BooleanField(default=False),
        ),
    ]
