# Generated by Django 6.0.4 on 2026-06-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_extend_class_time_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='exam_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='exam_ready_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
