# Generated by Django 6.0.4 on 2026-07-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_cleanup_pre_join_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['is_graduated', 'name']},
        ),
    ]
