# Generated by Django 6.0.4 on 2026-07-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_groupdayoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='coin_threshold',
        ),
    ]
