# Generated by Django 6.0.4 on 2026-08-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_remove_group_coin_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='sticker_count',
        ),
        migrations.DeleteModel(
            name='CoinTransaction',
        ),
    ]
