# Generated by Django 6.0.4 on 2026-08-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_remove_groupmembership_sticker_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
