# Generated by Django 6.0.4 on 2026-07-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Emoji, masalan: 🎁', max_length=8)),
                ('price', models.PositiveIntegerField(help_text='Narx — tangachada')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('snack', 'Yengil taom'), ('stationery', 'Kantselyariya'), ('merch', 'Merch'), ('discount', 'Chegirma'), ('other', 'Boshqa')], default='other', max_length=12)),
                ('status', models.CharField(choices=[('available', 'Sotuvda'), ('coming_soon', 'Tez kunda'), ('hidden', 'Yashirilgan')], default='coming_soon', max_length=12)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price', 'name'],
            },
        ),
    ]
