# Generated by Django 6.0.4 on 2026-08-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, help_text="Ixtiyoriy — rasm bo'lmasa icon ko'rsatiladi", null=True, upload_to='rewards/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='category',
            field=models.CharField(choices=[('snack', 'Yengil taom'), ('stationery', 'Kantselyariya'), ('merch', 'Merch'), ('discount', 'Chegirma'), ('coupon', 'Chegirma kuponi'), ('other', 'Boshqa')], default='other', max_length=12),
        ),
    ]
