# Generated by Django 6.0.4 on 2026-05-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_invitetoken_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='report_time',
            field=models.TimeField(blank=True, help_text='Daily report time in UTC (e.g. 15:00)', null=True),
        ),
    ]
