# Generated by Django 6.0.4 on 2026-05-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0003_add_report_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyTelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_groups', to='academies.academy')),
            ],
            options={
                'unique_together': {('academy', 'chat_id')},
            },
        ),
    ]
