# Generated by Django 6.0.4 on 2026-05-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0004_add_academy_telegram_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='logo',
        ),
    ]
