# Generated by Django 6.0.4 on 2026-05-02 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
        ('users', '0003_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='academies.academy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Admin'), ('parent', 'Parent')], default='student', max_length=10),
        ),
    ]
