# Generated by Django 6.0.4 on 2026-05-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
    ]
