# Generated by Django 6.0.4 on 2026-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_telegram_id_otp_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_lang',
            field=models.CharField(blank=True, default='uz', max_length=2, null=True),
        ),
    ]
