# Generated by Django 6.0.4 on 2026-05-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('score', 'Score Added'), ('absent', 'Marked Absent'), ('lesson', 'New Lesson'), ('announcement', 'Announcement')], max_length=20),
        ),
    ]
