# Generated by Django 6.0.4 on 2026-06-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_push_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('score', 'Score Added'), ('absent', 'Marked Absent'), ('lesson', 'New Lesson'), ('announcement', 'Announcement'), ('exam', 'Exam Result')], max_length=20),
        ),
    ]
