# Generated by Django 6.0.4 on 2026-07-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
