# Generated by Django 6.0.4 on 2026-07-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_lead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
